#ifndef PRAGMA_LH_LIB_H
#define PRAGMA_LH_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_LH_PROTOS_H
#include <clib/lh_protos.h>
#endif /* CLIB_LH_PROTOS_H */

/* "lh.library" */

/* Classic LhLib API (Holger Krekel 1990) + extended codec */

#pragma amicall(LhBase, 0x1E, CreateBuffer(d0))
#pragma amicall(LhBase, 0x24, DeleteBuffer(a0))
#pragma amicall(LhBase, 0x2A, LhEncode(a0))
#pragma amicall(LhBase, 0x30, LhDecode(a0))
/*--- functions in V2 or higher --- */
#pragma amicall(LhBase, 0x36, LhCompress(d0,a0))
#pragma amicall(LhBase, 0x3C, LhDecompress(d0,a0))

/* DOS.library-style archive access (LhArchive volume root) */

#pragma amicall(LhBase, 0x42, LhOpenArchive(d1,d0))
#pragma amicall(LhBase, 0x48, LhCloseArchive(a0))
#pragma amicall(LhBase, 0x4E, LhLock(a0,a1))
#pragma amicall(LhBase, 0x54, LhUnLock(a0))
#pragma amicall(LhBase, 0x5A, LhExamine(a0,a1))
#pragma amicall(LhBase, 0x60, LhExNext(a0,a1))
#pragma amicall(LhBase, 0x66, LhExAll(a0,d1,d0,d2,a1))
#pragma amicall(LhBase, 0x6C, LhExAllEnd(a0))
#pragma amicall(LhBase, 0x72, LhInfo(a0,a1))
#pragma amicall(LhBase, 0x78, LhOpenFromLock(a0,d0))
#pragma amicall(LhBase, 0x7E, LhOpen(a0,a1,d0))
#pragma amicall(LhBase, 0x84, LhRead(d1,a0,d0))
#pragma amicall(LhBase, 0x8A, LhWrite(d1,a0,d0))
#pragma amicall(LhBase, 0x90, LhClose(d1))
#pragma amicall(LhBase, 0x96, LhSeek(d1,d2,d0))
#pragma amicall(LhBase, 0x9C, LhNameFromLock(a0,a1,d0))
#pragma amicall(LhBase, 0xA2, LhAddEntryA(a0,a1,a2,d0,a3))
#if defined(__STORM__)
#pragma tagcall(LhBase, 0xA2, LhAddEntry(a0,a1,a2,d0,a3))
#endif /* __STORM__ */
#pragma amicall(LhBase, 0xA8, LhDeleteFile(a0,a1))
#pragma amicall(LhBase, 0xAE, LhConcatArchive(a0,a1))
#pragma amicall(LhBase, 0xB4, LhSetPassword(a0,a1))
#pragma amicall(LhBase, 0xBA, LhReadData(a0,a1,a2))
#pragma amicall(LhBase, 0xC0, LhExtractEntry(a0,a1,a2))
#pragma amicall(LhBase, 0xC6, LhTestEntry(a0,a1))
#pragma amicall(LhBase, 0xCC, LhPrintEntry(a0,a1))
#pragma amicall(LhBase, 0xD2, LhErr())

#endif /* PRAGMA_LH_LIB_H */
