#ifndef PRAGMAS_LH_PRAGMAS_H
#define PRAGMAS_LH_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_LH_PROTOS_H
#include <clib/lh_protos.h>
#endif /* CLIB_LH_PROTOS_H */

/* "lh.library" */

/* Classic LhLib API (Holger Krekel 1990) + extended codec */

#pragma libcall LhBase CreateBuffer 1E 001
#pragma libcall LhBase DeleteBuffer 24 801
#pragma libcall LhBase LhEncode 2A 801
#pragma libcall LhBase LhDecode 30 801
/*--- functions in V2 or higher --- */
#pragma libcall LhBase LhCompress 36 8002
#pragma libcall LhBase LhDecompress 3C 8002

/* DOS.library-style archive access (LhArchive volume root) */

#pragma libcall LhBase LhOpenArchive 42 0102
#pragma libcall LhBase LhCloseArchive 48 801
#pragma libcall LhBase LhLock 4E 9802
#pragma libcall LhBase LhUnLock 54 801
#pragma libcall LhBase LhExamine 5A 9802
#pragma libcall LhBase LhExNext 60 9802
#pragma libcall LhBase LhExAll 66 9201805
#pragma libcall LhBase LhExAllEnd 6C 801
#pragma libcall LhBase LhInfo 72 9802
#pragma libcall LhBase LhOpenFromLock 78 0802
#pragma libcall LhBase LhOpen 7E 09803
#pragma libcall LhBase LhRead 84 08103
#pragma libcall LhBase LhWrite 8A 08103
#pragma libcall LhBase LhClose 90 101
#pragma libcall LhBase LhSeek 96 02103
#pragma libcall LhBase LhNameFromLock 9C 09803
#pragma libcall LhBase LhAddEntryA A2 B0A9805
#if defined(__SASC_60)
#pragma tagcall LhBase LhAddEntry A2 B0A9805
#endif /* __SASC_60 */
#pragma libcall LhBase LhDeleteFile A8 9802
#pragma libcall LhBase LhConcatArchive AE 9802
#pragma libcall LhBase LhSetPassword B4 9802
#pragma libcall LhBase LhReadData BA A9803
#pragma libcall LhBase LhExtractEntry C0 A9803
#pragma libcall LhBase LhTestEntry C6 9802
#pragma libcall LhBase LhPrintEntry CC 9802
#pragma libcall LhBase LhErr D2 00

#endif /* PRAGMAS_LH_PRAGMAS_H */
