#ifndef INLINE_LH_H
#define INLINE_LH_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/* "lh.library" */

/* Classic LhLib API (Holger Krekel 1990) + extended codec */

#define CreateBuffer(OnlyDecode)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register LONG p0 __asm("d0") = (OnlyDecode);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DeleteBuffer(OldBuffer)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhBuffer *p0 __asm("a0") = (OldBuffer);   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define LhEncode(Buffer)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhBuffer *p0 __asm("a0") = (Buffer);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhDecode(Buffer)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhBuffer *p0 __asm("a0") = (Buffer);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

/*--- functions in V2 or higher --- */
#define LhCompress(Method, Buffer)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register LONG p0 __asm("d0") = (Method);   \
	register struct LhBuffer *p1 __asm("a0") = (Buffer);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhDecompress(Method, Buffer)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register LONG p0 __asm("d0") = (Method);   \
	register struct LhBuffer *p1 __asm("a0") = (Buffer);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* DOS.library-style archive access (LhArchive volume root) */

#define LhOpenArchive(Path, Mode)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register STRPTR p0 __asm("d1") = (Path);   \
	register LONG p1 __asm("d0") = (Mode);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhCloseArchive(Archive)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhLock(Archive, Name)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhUnLock(Lock)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhExamine(Lock, Fib)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register struct FileInfoBlock *p1 __asm("a1") = (Fib);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhExNext(Lock, Fib)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register struct FileInfoBlock *p1 __asm("a1") = (Fib);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhExAll(Lock, Buffer, Size, Type, Control)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register STRPTR p1 __asm("d1") = (Buffer);   \
	register LONG p2 __asm("d0") = (Size);   \
	register LONG p3 __asm("d2") = (Type);   \
	register struct ExAllControl *p4 __asm("a1") = (Control);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3), "r"(p4) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhExAllEnd(Lock)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhInfo(Lock, Info)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register struct InfoData *p1 __asm("a1") = (Info);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhOpenFromLock(Lock, Mode)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register LONG p1 __asm("d0") = (Mode);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhOpen(Archive, Name, Mode)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register LONG p2 __asm("d0") = (Mode);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhRead(Fh, Buffer, Len)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("d1") = (Fh);   \
	register APTR p1 __asm("a0") = (Buffer);   \
	register LONG p2 __asm("d0") = (Len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhWrite(Fh, Buffer, Len)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("d1") = (Fh);   \
	register APTR p1 __asm("a0") = (Buffer);   \
	register LONG p2 __asm("d0") = (Len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhClose(Fh)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("d1") = (Fh);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhSeek(Fh, Position, Mode)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("d1") = (Fh);   \
	register LONG p1 __asm("d2") = (Position);   \
	register LONG p2 __asm("d0") = (Mode);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhNameFromLock(Lock, Buffer, Len)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register BPTR p0 __asm("a0") = (Lock);   \
	register STRPTR p1 __asm("a1") = (Buffer);   \
	register LONG p2 __asm("d0") = (Len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhAddEntryA(Archive, Name, Data, DataLen, TagList)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR p2 __asm("a2") = (Data);   \
	register LONG p3 __asm("d0") = (DataLen);   \
	register struct TagItem *p4 __asm("a3") = (TagList);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3), "r"(p4) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define LhAddEntry(Archive, Name, Data, DataLen, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	LhAddEntryA((Archive), (Name), (Data), (DataLen), _argarray);   \
	r;   \
})
#endif

#define LhDeleteFile(Archive, Name)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-168:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhConcatArchive(Dest, SourcePath)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Dest);   \
	register STRPTR p1 __asm("a1") = (SourcePath);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-174:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhSetPassword(Archive, Password)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Password);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-180:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhReadData(Archive, Name, DataOut)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR *p2 __asm("a2") = (DataOut);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-186:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhExtractEntry(Archive, Name, DestPath)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register STRPTR p2 __asm("a2") = (DestPath);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-192:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhTestEntry(Archive, Name)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-198:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhPrintEntry(Archive, Name)    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register struct LhArchive *p0 __asm("a0") = (Archive);   \
	register STRPTR p1 __asm("a1") = (Name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-204:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define LhErr()    \
({  \
	register void *b __asm("a6") = LhBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-210:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


#endif /* INLINE_LH_H */
