#ifndef INLINE_LH_PROTOS_H
#define INLINE_LH_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/* "lh.library" */

/* Classic LhLib API (Holger Krekel 1990) + extended codec */

struct LhBuffer *__CreateBuffer(__reg("a6") void *, __reg("d0") LONG OnlyDecode)="\tjsr\t-30(a6)";
#define CreateBuffer(OnlyDecode) __CreateBuffer(LhBase, (OnlyDecode))

void __DeleteBuffer(__reg("a6") void *, __reg("a0") struct LhBuffer *OldBuffer)="\tjsr\t-36(a6)";
#define DeleteBuffer(OldBuffer) __DeleteBuffer(LhBase, (OldBuffer))

ULONG __LhEncode(__reg("a6") void *, __reg("a0") struct LhBuffer *Buffer)="\tjsr\t-42(a6)";
#define LhEncode(Buffer) __LhEncode(LhBase, (Buffer))

ULONG __LhDecode(__reg("a6") void *, __reg("a0") struct LhBuffer *Buffer)="\tjsr\t-48(a6)";
#define LhDecode(Buffer) __LhDecode(LhBase, (Buffer))

/*--- functions in V2 or higher --- */
ULONG __LhCompress(__reg("a6") void *, __reg("d0") LONG Method, __reg("a0") struct LhBuffer *Buffer)="\tjsr\t-54(a6)";
#define LhCompress(Method, Buffer) __LhCompress(LhBase, (Method), (Buffer))

ULONG __LhDecompress(__reg("a6") void *, __reg("d0") LONG Method, __reg("a0") struct LhBuffer *Buffer)="\tjsr\t-60(a6)";
#define LhDecompress(Method, Buffer) __LhDecompress(LhBase, (Method), (Buffer))


/* DOS.library-style archive access (LhArchive volume root) */

struct LhArchive *__LhOpenArchive(__reg("a6") void *, __reg("d1") STRPTR Path, __reg("d0") LONG Mode)="\tjsr\t-66(a6)";
#define LhOpenArchive(Path, Mode) __LhOpenArchive(LhBase, (Path), (Mode))

LONG __LhCloseArchive(__reg("a6") void *, __reg("a0") struct LhArchive *Archive)="\tjsr\t-72(a6)";
#define LhCloseArchive(Archive) __LhCloseArchive(LhBase, (Archive))

BPTR __LhLock(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name)="\tjsr\t-78(a6)";
#define LhLock(Archive, Name) __LhLock(LhBase, (Archive), (Name))

LONG __LhUnLock(__reg("a6") void *, __reg("a0") BPTR Lock)="\tjsr\t-84(a6)";
#define LhUnLock(Lock) __LhUnLock(LhBase, (Lock))

LONG __LhExamine(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("a1") struct FileInfoBlock *Fib)="\tjsr\t-90(a6)";
#define LhExamine(Lock, Fib) __LhExamine(LhBase, (Lock), (Fib))

LONG __LhExNext(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("a1") struct FileInfoBlock *Fib)="\tjsr\t-96(a6)";
#define LhExNext(Lock, Fib) __LhExNext(LhBase, (Lock), (Fib))

LONG __LhExAll(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("d1") STRPTR Buffer, __reg("d0") LONG Size, __reg("d2") LONG Type, __reg("a1") struct ExAllControl *Control)="\tjsr\t-102(a6)";
#define LhExAll(Lock, Buffer, Size, Type, Control) __LhExAll(LhBase, (Lock), (Buffer), (Size), (Type), (Control))

LONG __LhExAllEnd(__reg("a6") void *, __reg("a0") BPTR Lock)="\tjsr\t-108(a6)";
#define LhExAllEnd(Lock) __LhExAllEnd(LhBase, (Lock))

LONG __LhInfo(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("a1") struct InfoData *Info)="\tjsr\t-114(a6)";
#define LhInfo(Lock, Info) __LhInfo(LhBase, (Lock), (Info))

BPTR __LhOpenFromLock(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("d0") LONG Mode)="\tjsr\t-120(a6)";
#define LhOpenFromLock(Lock, Mode) __LhOpenFromLock(LhBase, (Lock), (Mode))

BPTR __LhOpen(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name, __reg("d0") LONG Mode)="\tjsr\t-126(a6)";
#define LhOpen(Archive, Name, Mode) __LhOpen(LhBase, (Archive), (Name), (Mode))

LONG __LhRead(__reg("a6") void *, __reg("d1") BPTR Fh, __reg("a0") APTR Buffer, __reg("d0") LONG Len)="\tjsr\t-132(a6)";
#define LhRead(Fh, Buffer, Len) __LhRead(LhBase, (Fh), (Buffer), (Len))

LONG __LhWrite(__reg("a6") void *, __reg("d1") BPTR Fh, __reg("a0") APTR Buffer, __reg("d0") LONG Len)="\tjsr\t-138(a6)";
#define LhWrite(Fh, Buffer, Len) __LhWrite(LhBase, (Fh), (Buffer), (Len))

LONG __LhClose(__reg("a6") void *, __reg("d1") BPTR Fh)="\tjsr\t-144(a6)";
#define LhClose(Fh) __LhClose(LhBase, (Fh))

LONG __LhSeek(__reg("a6") void *, __reg("d1") BPTR Fh, __reg("d2") LONG Position, __reg("d0") LONG Mode)="\tjsr\t-150(a6)";
#define LhSeek(Fh, Position, Mode) __LhSeek(LhBase, (Fh), (Position), (Mode))

LONG __LhNameFromLock(__reg("a6") void *, __reg("a0") BPTR Lock, __reg("a1") STRPTR Buffer, __reg("d0") LONG Len)="\tjsr\t-156(a6)";
#define LhNameFromLock(Lock, Buffer, Len) __LhNameFromLock(LhBase, (Lock), (Buffer), (Len))

LONG __LhAddEntryA(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name, __reg("a2") APTR Data, __reg("d0") LONG DataLen, __reg("a3") struct TagItem *TagList)="\tjsr\t-162(a6)";
#define LhAddEntryA(Archive, Name, Data, DataLen, TagList) __LhAddEntryA(LhBase, (Archive), (Name), (Data), (DataLen), (TagList))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __LhAddEntry(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name, __reg("a2") APTR Data, __reg("d0") LONG DataLen, ...)="\tmove.l\ta3,-(a7)\n\tlea\t4(a7),a3\n\tjsr\t-162(a6)\n\tmovea.l\t(a7)+,a3";
#define LhAddEntry(...) __LhAddEntry(LhBase, __VA_ARGS__)
#endif

LONG __LhDeleteFile(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name)="\tjsr\t-168(a6)";
#define LhDeleteFile(Archive, Name) __LhDeleteFile(LhBase, (Archive), (Name))

LONG __LhConcatArchive(__reg("a6") void *, __reg("a0") struct LhArchive *Dest, __reg("a1") STRPTR SourcePath)="\tjsr\t-174(a6)";
#define LhConcatArchive(Dest, SourcePath) __LhConcatArchive(LhBase, (Dest), (SourcePath))

LONG __LhSetPassword(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Password)="\tjsr\t-180(a6)";
#define LhSetPassword(Archive, Password) __LhSetPassword(LhBase, (Archive), (Password))

LONG __LhReadData(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name, __reg("a2") APTR *DataOut)="\tjsr\t-186(a6)";
#define LhReadData(Archive, Name, DataOut) __LhReadData(LhBase, (Archive), (Name), (DataOut))

LONG __LhExtractEntry(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name, __reg("a2") STRPTR DestPath)="\tjsr\t-192(a6)";
#define LhExtractEntry(Archive, Name, DestPath) __LhExtractEntry(LhBase, (Archive), (Name), (DestPath))

LONG __LhTestEntry(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name)="\tjsr\t-198(a6)";
#define LhTestEntry(Archive, Name) __LhTestEntry(LhBase, (Archive), (Name))

LONG __LhPrintEntry(__reg("a6") void *, __reg("a0") struct LhArchive *Archive, __reg("a1") STRPTR Name)="\tjsr\t-204(a6)";
#define LhPrintEntry(Archive, Name) __LhPrintEntry(LhBase, (Archive), (Name))

LONG __LhErr(__reg("a6") void *)="\tjsr\t-210(a6)";
#define LhErr() __LhErr(LhBase)


#endif /* INLINE_LH_PROTOS_H */
