#ifndef PROTO_LH_H
#define PROTO_LH_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/lh_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * LhBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_LH_PRAGMAS_H
#include <pragmas/lh_pragmas.h>
#endif /* PRAGMAS_LH_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_LH_LIB_H
#include <pragma/lh_lib.h>
#endif /* PRAGMA_LH_LIB_H */

#elif defined(__VBCC__)

#include <clib/lh_protos.h>

#ifndef INLINE_LH_PROTOS_H
#include <inline/lh_protos.h>
#endif /* INLINE_LH_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_LH_H
#include <inline/lh.h>
#endif /* INLINE_LH_H */
#else
#include <clib/lh_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/lh_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_LH_H */
